import type { Element } from './elements';

export type Rarity = 'common' | 'uncommon' | 'rare' | 'legendary';

export const RARITY_NAME: Record<Rarity, string> = {
  common: '常見',
  uncommon: '少見',
  rare: '稀有',
  legendary: '傳說',
};

/** 用來組合 SVG 外觀的部件（見 ui/CreatureSvg.vue） */
export interface CreatureLook {
  body: 'round' | 'bean' | 'tall' | 'drop' | 'blob';
  color: string;
  belly: string;
  eyes: 'dot' | 'big' | 'sleepy' | 'happy';
  mouth: 'smile' | 'open' | 'cat' | 'tiny';
  parts: CreaturePart[];
  /** 配件顏色（帽子、殼、角等），未指定時用身體顏色加深 */
  accent?: string;
  cheeks?: boolean;
}

export type CreaturePart =
  | 'flame'
  | 'sprout'
  | 'bubbles'
  | 'bulb'
  | 'cap'
  | 'horns'
  | 'ears'
  | 'shell'
  | 'star'
  | 'wings'
  | 'moss'
  | 'leafEars'
  | 'antenna'
  | 'fins'
  | 'crown'
  | 'tail'
  | 'handle'
  | 'clock'
  | 'spots'
  | 'cherry'
  | 'brows'
  | 'tiara'
  | 'cloud'
  | 'spikes'
  | 'swirl'
  | 'snowflake'
  | 'scarf'
  | 'rainbow'
  | 'stripes'
  | 'headband'
  | 'cape'
  | 'patches'
  | 'helmet'
  | 'crescent'
  | 'bow'
  | 'halo';

export interface Species {
  /** 圖鑑編號 */
  id: number;
  name: string;
  /** 英文名字，本身就是一個單字 */
  english: string;
  /** 英文名字的中文意思 */
  meaning: string;
  element: Element;
  rarity: Rarity;
  description: string;
  baseHp: number;
  baseAtk: number;
  look: CreatureLook;
}

/** 所有字靈；新增字靈只要在這裡加一筆並放進 areas.ts 的棲息地 */
export const SPECIES: readonly Species[] = [
  {
    id: 1,
    name: '炭炭',
    english: 'Ember',
    meaning: '餘燼',
    element: 'fire',
    rarity: 'rare',
    description: '一顆會冒火星的小煤炭。開心的時候頭上的火會變成愛心形狀。',
    baseHp: 30,
    baseAtk: 11,
    look: {
      body: 'round',
      color: '#44403c',
      belly: '#78716c',
      eyes: 'big',
      mouth: 'open',
      parts: ['flame'],
      cheeks: true,
    },
  },
  {
    id: 2,
    name: '啵啵',
    english: 'Bubble',
    meaning: '泡泡',
    element: 'water',
    rarity: 'rare',
    description: '頭上一直冒泡泡的小水母。泡泡破掉時會發出「啵」的聲音。',
    baseHp: 33,
    baseAtk: 10,
    look: {
      body: 'drop',
      color: '#38bdf8',
      belly: '#bae6fd',
      eyes: 'big',
      mouth: 'smile',
      parts: ['bubbles'],
      cheeks: true,
    },
  },
  {
    id: 3,
    name: '苔苔',
    english: 'Moss',
    meaning: '青苔',
    element: 'grass',
    rarity: 'rare',
    description: '背上長滿青苔的圓滾滾小熊。下雨天會特別有精神。',
    baseHp: 36,
    baseAtk: 9,
    look: {
      body: 'round',
      color: '#a16207',
      belly: '#fde68a',
      eyes: 'dot',
      mouth: 'cat',
      parts: ['ears', 'moss'],
      cheeks: true,
    },
  },
  {
    id: 4,
    name: '石帽',
    english: 'Pebble',
    meaning: '小石頭',
    element: 'earth',
    rarity: 'common',
    description: '戴著石頭帽子的蘑菇。害羞的時候會把整個身體縮進帽子裡。',
    baseHp: 30,
    baseAtk: 8,
    look: {
      body: 'bean',
      color: '#fef3c7',
      belly: '#fffbeb',
      eyes: 'sleepy',
      mouth: 'tiny',
      accent: '#78716c',
      parts: ['cap'],
    },
  },
  {
    id: 5,
    name: '豆芽',
    english: 'Seed',
    meaning: '種子',
    element: 'grass',
    rarity: 'common',
    description: '頭上冒出一片小嫩芽的豆子。曬太陽的時候嫩芽會慢慢長高。',
    baseHp: 26,
    baseAtk: 8,
    look: {
      body: 'bean',
      color: '#86efac',
      belly: '#dcfce7',
      eyes: 'happy',
      mouth: 'smile',
      parts: ['sprout'],
      cheeks: true,
    },
  },
  {
    id: 6,
    name: '閃閃',
    english: 'Spark',
    meaning: '火花',
    element: 'thunder',
    rarity: 'uncommon',
    description: '尾巴是一顆燈泡的小鳥。晚上會幫迷路的旅人照亮道路。',
    baseHp: 25,
    baseAtk: 11,
    look: {
      body: 'round',
      color: '#fde047',
      belly: '#fef9c3',
      eyes: 'big',
      mouth: 'open',
      accent: '#f59e0b',
      parts: ['wings', 'bulb'],
    },
  },
  {
    id: 7,
    name: '鈕鈕',
    english: 'Button',
    meaning: '鈕扣',
    element: 'earth',
    rarity: 'common',
    description: '背殼像鈕扣一樣圓的小甲蟲。常常被誤認成掉在地上的鈕扣。',
    baseHp: 28,
    baseAtk: 9,
    look: {
      body: 'bean',
      color: '#dc2626',
      belly: '#fecaca',
      eyes: 'dot',
      mouth: 'tiny',
      accent: '#111827',
      parts: ['antenna', 'shell'],
    },
  },
  {
    id: 8,
    name: '暖陽',
    english: 'Sun',
    meaning: '太陽',
    element: 'light',
    rarity: 'rare',
    description: '只在晴天出現的小太陽。靠近牠會覺得全身暖呼呼的。',
    baseHp: 30,
    baseAtk: 12,
    look: {
      body: 'round',
      color: '#fbbf24',
      belly: '#fef3c7',
      eyes: 'happy',
      mouth: 'smile',
      accent: '#f59e0b',
      parts: ['crown'],
      cheeks: true,
    },
  },
  {
    id: 9,
    name: '葉葉',
    english: 'Leaf',
    meaning: '葉子',
    element: 'grass',
    rarity: 'common',
    description: '耳朵是兩片葉子的小兔子。風一吹耳朵就會沙沙作響。',
    baseHp: 28,
    baseAtk: 9,
    look: {
      body: 'tall',
      color: '#bbf7d0',
      belly: '#f0fdf4',
      eyes: 'dot',
      mouth: 'cat',
      parts: ['leafEars'],
      cheeks: true,
    },
  },
  {
    id: 10,
    name: '橡橡',
    english: 'Acorn',
    meaning: '橡實',
    element: 'earth',
    rarity: 'common',
    description: '住在大樹下的橡實精靈。最喜歡把自己埋進落葉堆裡。',
    baseHp: 32,
    baseAtk: 8,
    look: {
      body: 'drop',
      color: '#b45309',
      belly: '#fcd34d',
      eyes: 'big',
      mouth: 'tiny',
      accent: '#78350f',
      parts: ['cap'],
    },
  },
  {
    id: 11,
    name: '螢螢',
    english: 'Glow',
    meaning: '發光',
    element: 'light',
    rarity: 'uncommon',
    description: '會發光的小精靈。森林的夜晚都靠牠們點亮。',
    baseHp: 24,
    baseAtk: 12,
    look: {
      body: 'round',
      color: '#a7f3d0',
      belly: '#ecfdf5',
      eyes: 'happy',
      mouth: 'smile',
      accent: '#34d399',
      parts: ['antenna', 'wings', 'bulb'],
    },
  },
  {
    id: 12,
    name: '燭燭',
    english: 'Candle',
    meaning: '蠟燭',
    element: 'fire',
    rarity: 'uncommon',
    description: '頭頂一小撮火苗的蠟燭精靈。跑太快的話火會熄掉，所以總是慢慢走。',
    baseHp: 26,
    baseAtk: 12,
    look: {
      body: 'tall',
      color: '#fef2f2',
      belly: '#fee2e2',
      eyes: 'sleepy',
      mouth: 'tiny',
      accent: '#fb923c',
      parts: ['flame'],
    },
  },
  {
    id: 13,
    name: '雲雲',
    english: 'Cloud',
    meaning: '雲',
    element: 'thunder',
    rarity: 'rare',
    description: '軟綿綿的雲朵。生氣的時候會變成灰色，還會打雷。',
    baseHp: 30,
    baseAtk: 13,
    look: {
      body: 'blob',
      color: '#e2e8f0',
      belly: '#f8fafc',
      eyes: 'dot',
      mouth: 'open',
      accent: '#facc15',
      parts: ['horns'],
      cheeks: true,
    },
  },
  {
    id: 14,
    name: '貝貝',
    english: 'Shell',
    meaning: '貝殼',
    element: 'water',
    rarity: 'common',
    description: '背著漂亮貝殼的小寄居蟹。會一直找更大的貝殼來換。',
    baseHp: 32,
    baseAtk: 8,
    look: {
      body: 'bean',
      color: '#fb923c',
      belly: '#ffedd5',
      eyes: 'big',
      mouth: 'tiny',
      accent: '#fde68a',
      parts: ['shell', 'antenna'],
    },
  },
  {
    id: 15,
    name: '珊珊',
    english: 'Coral',
    meaning: '珊瑚',
    element: 'water',
    rarity: 'common',
    description: '頭上長著珊瑚角的小魚。游泳的時候會留下一串彩色泡泡。',
    baseHp: 27,
    baseAtk: 10,
    look: {
      body: 'drop',
      color: '#f9a8d4',
      belly: '#fce7f3',
      eyes: 'dot',
      mouth: 'smile',
      accent: '#f472b6',
      parts: ['horns', 'fins'],
    },
  },
  {
    id: 16,
    name: '沙沙',
    english: 'Sand',
    meaning: '沙子',
    element: 'earth',
    rarity: 'common',
    description: '用沙子堆成的小怪物。浪打過來的時候會趕快逃跑。',
    baseHp: 30,
    baseAtk: 9,
    look: {
      body: 'blob',
      color: '#fde68a',
      belly: '#fef9c3',
      eyes: 'sleepy',
      mouth: 'cat',
      parts: ['ears'],
    },
  },
  {
    id: 17,
    name: '風箏',
    english: 'Kite',
    meaning: '風箏',
    element: 'thunder',
    rarity: 'uncommon',
    description: '像風箏一樣在海風裡飛的小鳥。翅膀上的電可以讓牠飛很久。',
    baseHp: 24,
    baseAtk: 12,
    look: {
      body: 'round',
      color: '#60a5fa',
      belly: '#dbeafe',
      eyes: 'big',
      mouth: 'open',
      accent: '#1d4ed8',
      parts: ['wings', 'antenna'],
    },
  },
  {
    id: 18,
    name: '星咩',
    english: 'Star',
    meaning: '星星',
    element: 'light',
    rarity: 'rare',
    description: '毛是星星形狀的小羊。晚上在海邊數星星的時候最容易遇到。',
    baseHp: 32,
    baseAtk: 12,
    look: {
      body: 'blob',
      color: '#fefce8',
      belly: '#ffffff',
      eyes: 'happy',
      mouth: 'cat',
      accent: '#facc15',
      parts: ['horns', 'star'],
      cheeks: true,
    },
  },
  {
    id: 19,
    name: '杯杯',
    english: 'Cup',
    meaning: '杯子',
    element: 'water',
    rarity: 'common',
    description: '會把自己裝滿水的小杯子。口渴的時候牠會分你一口。',
    baseHp: 30,
    baseAtk: 9,
    look: {
      body: 'tall',
      color: '#e0f2fe',
      belly: '#bae6fd',
      eyes: 'big',
      mouth: 'smile',
      accent: '#0284c7',
      parts: ['handle', 'bubbles'],
      cheeks: true,
    },
  },
  {
    id: 20,
    name: '匙匙',
    english: 'Key',
    meaning: '鑰匙',
    element: 'thunder',
    rarity: 'common',
    description: '尾巴像鑰匙的小精靈。聽說牠能打開任何一扇門。',
    baseHp: 26,
    baseAtk: 11,
    look: {
      body: 'round',
      color: '#fde047',
      belly: '#fef9c3',
      eyes: 'dot',
      mouth: 'cat',
      accent: '#a16207',
      parts: ['horns', 'tail'],
    },
  },
  {
    id: 21,
    name: '吐吐',
    english: 'Toast',
    meaning: '吐司',
    element: 'fire',
    rarity: 'common',
    description: '剛烤好的吐司精靈，身上總是暖暖的，還有奶油香味。',
    baseHp: 28,
    baseAtk: 10,
    look: {
      body: 'bean',
      color: '#f59e0b',
      belly: '#fde68a',
      eyes: 'sleepy',
      mouth: 'smile',
      parts: ['flame'],
      cheeks: true,
    },
  },
  {
    id: 22,
    name: '枕枕',
    english: 'Pillow',
    meaning: '枕頭',
    element: 'light',
    rarity: 'uncommon',
    description: '軟綿綿的枕頭精靈。靠著牠睡覺會做好夢。',
    baseHp: 34,
    baseAtk: 9,
    look: {
      body: 'blob',
      color: '#f8fafc',
      belly: '#e2e8f0',
      eyes: 'sleepy',
      mouth: 'tiny',
      accent: '#f472b6',
      parts: ['bow', 'star'],
      cheeks: true,
    },
  },
  {
    id: 23,
    name: '鐘鐘',
    english: 'Clock',
    meaning: '時鐘',
    element: 'earth',
    rarity: 'rare',
    description: '肚子上有時鐘的精靈，從來不會遲到。',
    baseHp: 34,
    baseAtk: 11,
    look: {
      body: 'tall',
      color: '#d6d3d1',
      belly: '#ffffff',
      eyes: 'big',
      mouth: 'tiny',
      accent: '#57534e',
      parts: ['clock', 'antenna'],
    },
  },
  {
    id: 24,
    name: '糖糖',
    english: 'Candy',
    meaning: '糖果',
    element: 'light',
    rarity: 'common',
    description: '甜甜的糖果精靈，心情好的時候身上會出現彩色條紋。',
    baseHp: 26,
    baseAtk: 10,
    look: {
      body: 'round',
      color: '#fbcfe8',
      belly: '#ffffff',
      eyes: 'happy',
      mouth: 'smile',
      accent: '#ec4899',
      parts: ['bow', 'stripes'],
      cheeks: true,
    },
  },
  {
    id: 25,
    name: '餅餅',
    english: 'Cookie',
    meaning: '餅乾',
    element: 'earth',
    rarity: 'common',
    description: '身上有巧克力豆的餅乾精靈。咬一口會發出喀滋聲。',
    baseHp: 30,
    baseAtk: 9,
    look: {
      body: 'bean',
      color: '#d97706',
      belly: '#fcd34d',
      eyes: 'dot',
      mouth: 'cat',
      accent: '#451a03',
      parts: ['spots'],
    },
  },
  {
    id: 26,
    name: '果凍',
    english: 'Jelly',
    meaning: '果凍',
    element: 'water',
    rarity: 'common',
    description: 'Q 彈的果凍精靈，頭上頂著一顆櫻桃。',
    baseHp: 32,
    baseAtk: 9,
    look: {
      body: 'bean',
      color: '#5eead4',
      belly: '#ccfbf1',
      eyes: 'big',
      mouth: 'open',
      parts: ['cherry'],
      cheeks: true,
    },
  },
  {
    id: 27,
    name: '辣辣',
    english: 'Pepper',
    meaning: '辣椒',
    element: 'fire',
    rarity: 'uncommon',
    description: '脾氣火爆的辣椒精靈。靠太近會辣到流眼淚。',
    baseHp: 25,
    baseAtk: 13,
    look: {
      body: 'tall',
      color: '#ef4444',
      belly: '#fecaca',
      eyes: 'big',
      mouth: 'open',
      parts: ['sprout', 'brows'],
    },
  },
  {
    id: 28,
    name: '蛋糕王',
    english: 'Cake',
    meaning: '蛋糕',
    element: 'light',
    rarity: 'rare',
    description: '戴著皇冠的蛋糕精靈，是甜點工坊的國王。',
    baseHp: 36,
    baseAtk: 12,
    look: {
      body: 'bean',
      color: '#fef3c7',
      belly: '#fbcfe8',
      eyes: 'happy',
      mouth: 'smile',
      accent: '#f59e0b',
      parts: ['tiara', 'stripes'],
      cheeks: true,
    },
  },
  {
    id: 29,
    name: '雨滴',
    english: 'Rain',
    meaning: '雨',
    element: 'water',
    rarity: 'common',
    description: '頂著一朵小雲的雨滴精靈。走到哪裡就下到哪裡。',
    baseHp: 28,
    baseAtk: 10,
    look: {
      body: 'drop',
      color: '#3b82f6',
      belly: '#bfdbfe',
      eyes: 'sleepy',
      mouth: 'tiny',
      parts: ['cloud'],
    },
  },
  {
    id: 30,
    name: '岩岩',
    english: 'Rock',
    meaning: '岩石',
    element: 'earth',
    rarity: 'common',
    description: '背上長著尖尖石頭的精靈，非常非常硬。',
    baseHp: 36,
    baseAtk: 9,
    look: {
      body: 'blob',
      color: '#a8a29e',
      belly: '#d6d3d1',
      eyes: 'dot',
      mouth: 'tiny',
      accent: '#57534e',
      parts: ['spikes'],
    },
  },
  {
    id: 31,
    name: '旋旋',
    english: 'Wind',
    meaning: '風',
    element: 'thunder',
    rarity: 'common',
    description: '身上會捲起小旋風的精靈，跑得比誰都快。',
    baseHp: 25,
    baseAtk: 12,
    look: {
      body: 'round',
      color: '#e0f2fe',
      belly: '#ffffff',
      eyes: 'happy',
      mouth: 'open',
      accent: '#0ea5e9',
      parts: ['swirl', 'wings'],
    },
  },
  {
    id: 32,
    name: '雪雪',
    english: 'Snow',
    meaning: '雪',
    element: 'water',
    rarity: 'uncommon',
    description: '圍著紅圍巾的雪人精靈。冬天的時候最有精神。',
    baseHp: 32,
    baseAtk: 11,
    look: {
      body: 'round',
      color: '#ffffff',
      belly: '#e0f2fe',
      eyes: 'dot',
      mouth: 'smile',
      accent: '#ef4444',
      parts: ['snowflake', 'scarf'],
      cheeks: true,
    },
  },
  {
    id: 33,
    name: '彩虹',
    english: 'Rainbow',
    meaning: '彩虹',
    element: 'light',
    rarity: 'rare',
    description: '雨停之後才會出現的精靈，背著一道彩虹。',
    baseHp: 32,
    baseAtk: 13,
    look: {
      body: 'blob',
      color: '#ffffff',
      belly: '#fef9c3',
      eyes: 'happy',
      mouth: 'smile',
      parts: ['rainbow'],
      cheeks: true,
    },
  },
  {
    id: 34,
    name: '球球',
    english: 'Ball',
    meaning: '球',
    element: 'earth',
    rarity: 'common',
    description: '圓滾滾的籃球精靈。一拍就會跳得好高。',
    baseHp: 30,
    baseAtk: 10,
    look: {
      body: 'round',
      color: '#f97316',
      belly: '#fed7aa',
      eyes: 'big',
      mouth: 'open',
      accent: '#7c2d12',
      parts: ['stripes'],
    },
  },
  {
    id: 35,
    name: '踢踢',
    english: 'Kick',
    meaning: '踢',
    element: 'fire',
    rarity: 'common',
    description: '綁著頭帶的足球小將，最喜歡踢球。',
    baseHp: 28,
    baseAtk: 12,
    look: {
      body: 'tall',
      color: '#fb7185',
      belly: '#ffe4e6',
      eyes: 'dot',
      mouth: 'smile',
      accent: '#dc2626',
      parts: ['headband'],
      cheeks: true,
    },
  },
  {
    id: 36,
    name: '泳泳',
    english: 'Swim',
    meaning: '游泳',
    element: 'water',
    rarity: 'common',
    description: '戴著泳帽的小魚精靈，可以游一整天都不累。',
    baseHp: 28,
    baseAtk: 11,
    look: {
      body: 'bean',
      color: '#0ea5e9',
      belly: '#e0f2fe',
      eyes: 'big',
      mouth: 'smile',
      accent: '#fde047',
      parts: ['headband', 'fins'],
    },
  },
  {
    id: 37,
    name: '跳跳',
    english: 'Jump',
    meaning: '跳',
    element: 'grass',
    rarity: 'uncommon',
    description: '會跳很高的蚱蜢精靈。一跳就能跳過一棵樹。',
    baseHp: 26,
    baseAtk: 13,
    look: {
      body: 'tall',
      color: '#84cc16',
      belly: '#ecfccb',
      eyes: 'big',
      mouth: 'cat',
      accent: '#3f6212',
      parts: ['antenna', 'wings'],
    },
  },
  {
    id: 38,
    name: '英英',
    english: 'Hero',
    meaning: '英雄',
    element: 'light',
    rarity: 'rare',
    description: '披著紅披風的小英雄，總是第一個跑來幫忙。',
    baseHp: 36,
    baseAtk: 13,
    look: {
      body: 'round',
      color: '#fde68a',
      belly: '#ffffff',
      eyes: 'big',
      mouth: 'smile',
      accent: '#dc2626',
      parts: ['cape', 'headband'],
      cheeks: true,
    },
  },
  {
    id: 39,
    name: '蛙蛙',
    english: 'Frog',
    meaning: '青蛙',
    element: 'water',
    rarity: 'common',
    description: '住在叢林池塘的青蛙精靈，叫聲非常響亮。',
    baseHp: 30,
    baseAtk: 10,
    look: {
      body: 'bean',
      color: '#22c55e',
      belly: '#bbf7d0',
      eyes: 'big',
      mouth: 'cat',
      parts: ['ears'],
      cheeks: true,
    },
  },
  {
    id: 40,
    name: '猴猴',
    english: 'Monkey',
    meaning: '猴子',
    element: 'grass',
    rarity: 'common',
    description: '很愛惡作劇的猴子精靈，會用尾巴倒掛在樹上。',
    baseHp: 28,
    baseAtk: 11,
    look: {
      body: 'round',
      color: '#a16207',
      belly: '#fde68a',
      eyes: 'dot',
      mouth: 'smile',
      parts: ['ears', 'tail'],
      cheeks: true,
    },
  },
  {
    id: 41,
    name: '熊貓',
    english: 'Panda',
    meaning: '熊貓',
    element: 'earth',
    rarity: 'common',
    description: '吃竹子吃到睡著的熊貓精靈。',
    baseHp: 38,
    baseAtk: 9,
    look: {
      body: 'round',
      color: '#ffffff',
      belly: '#f1f5f9',
      eyes: 'dot',
      mouth: 'cat',
      accent: '#1f2937',
      parts: ['patches'],
      cheeks: true,
    },
  },
  {
    id: 42,
    name: '虎虎',
    english: 'Tiger',
    meaning: '老虎',
    element: 'fire',
    rarity: 'uncommon',
    description: '身上有條紋的小老虎，吼叫聲很有氣勢。',
    baseHp: 30,
    baseAtk: 14,
    look: {
      body: 'round',
      color: '#fb923c',
      belly: '#fff7ed',
      eyes: 'big',
      mouth: 'cat',
      accent: '#431407',
      parts: ['ears', 'stripes'],
    },
  },
  {
    id: 43,
    name: '龍龍',
    english: 'Dragon',
    meaning: '龍',
    element: 'thunder',
    rarity: 'rare',
    description: '會噴出閃電的小龍，是叢林裡最強的字靈。',
    baseHp: 36,
    baseAtk: 15,
    look: {
      body: 'tall',
      color: '#fbbf24',
      belly: '#fef3c7',
      eyes: 'big',
      mouth: 'open',
      accent: '#b45309',
      parts: ['spikes', 'horns', 'wings', 'tail'],
    },
  },
  {
    id: 44,
    name: '冠冠',
    english: 'Crown',
    meaning: '皇冠',
    element: 'earth',
    rarity: 'common',
    description: '戴著大皇冠的精靈，其實只是很喜歡亮晶晶的東西。',
    baseHp: 32,
    baseAtk: 11,
    look: {
      body: 'bean',
      color: '#fcd34d',
      belly: '#fef9c3',
      eyes: 'sleepy',
      mouth: 'tiny',
      accent: '#dc2626',
      parts: ['tiara'],
    },
  },
  {
    id: 45,
    name: '影影',
    english: 'Shadow',
    meaning: '影子',
    element: 'thunder',
    rarity: 'common',
    description: '躲在影子裡的精靈，眼睛會發出黃光。',
    baseHp: 26,
    baseAtk: 14,
    look: {
      body: 'blob',
      color: '#475569',
      belly: '#64748b',
      eyes: 'big',
      mouth: 'open',
      accent: '#facc15',
      parts: ['horns'],
    },
  },
  {
    id: 46,
    name: '騎騎',
    english: 'Knight',
    meaning: '騎士',
    element: 'earth',
    rarity: 'uncommon',
    description: '守護城堡的小騎士，頭盔上有一根紅羽毛。',
    baseHp: 38,
    baseAtk: 13,
    look: {
      body: 'tall',
      color: '#94a3b8',
      belly: '#cbd5e1',
      eyes: 'dot',
      mouth: 'tiny',
      accent: '#64748b',
      parts: ['helmet'],
    },
  },
  {
    id: 47,
    name: '月月',
    english: 'Moon',
    meaning: '月亮',
    element: 'light',
    rarity: 'uncommon',
    description: '頭上掛著彎彎月亮的精靈，晚上會發出微光。',
    baseHp: 30,
    baseAtk: 14,
    look: {
      body: 'round',
      color: '#fef9c3',
      belly: '#ffffff',
      eyes: 'sleepy',
      mouth: 'smile',
      accent: '#facc15',
      parts: ['crescent', 'star'],
      cheeks: true,
    },
  },
  {
    id: 48,
    name: '彗彗',
    english: 'Comet',
    meaning: '彗星',
    element: 'fire',
    rarity: 'rare',
    description: '拖著長長火焰尾巴的彗星精靈，一年只出現一次。',
    baseHp: 32,
    baseAtk: 16,
    look: {
      body: 'drop',
      color: '#fb923c',
      belly: '#fde68a',
      eyes: 'big',
      mouth: 'open',
      accent: '#dc2626',
      parts: ['flame', 'tail'],
    },
  },
  {
    id: 49,
    name: '禮禮',
    english: 'Gift',
    meaning: '禮物',
    element: 'light',
    rarity: 'common',
    description: '綁著大蝴蝶結的禮物精靈，打開會有驚喜。',
    baseHp: 32,
    baseAtk: 12,
    look: {
      body: 'bean',
      color: '#34d399',
      belly: '#d1fae5',
      eyes: 'happy',
      mouth: 'smile',
      accent: '#ef4444',
      parts: ['bow', 'stripes'],
      cheeks: true,
    },
  },
  {
    id: 50,
    name: '燈燈',
    english: 'Lantern',
    meaning: '燈籠',
    element: 'fire',
    rarity: 'common',
    description: '節慶時會亮起來的燈籠精靈。',
    baseHp: 30,
    baseAtk: 13,
    look: {
      body: 'tall',
      color: '#ef4444',
      belly: '#fecaca',
      eyes: 'happy',
      mouth: 'smile',
      accent: '#facc15',
      parts: ['stripes', 'flame'],
      cheeks: true,
    },
  },
  {
    id: 51,
    name: '鈴鈴',
    english: 'Bell',
    meaning: '鈴鐺',
    element: 'earth',
    rarity: 'common',
    description: '一搖就會叮噹響的鈴鐺精靈。',
    baseHp: 34,
    baseAtk: 12,
    look: {
      body: 'drop',
      color: '#fbbf24',
      belly: '#fef3c7',
      eyes: 'dot',
      mouth: 'open',
      accent: '#dc2626',
      parts: ['bow'],
    },
  },
  {
    id: 52,
    name: '煙煙',
    english: 'Firework',
    meaning: '煙火',
    element: 'thunder',
    rarity: 'uncommon',
    description: '身上會爆出光芒的煙火精靈，最喜歡熱鬧。',
    baseHp: 28,
    baseAtk: 16,
    look: {
      body: 'round',
      color: '#1e3a8a',
      belly: '#3b82f6',
      eyes: 'big',
      mouth: 'open',
      accent: '#f472b6',
      parts: ['crown', 'star'],
    },
  },
  {
    id: 53,
    name: '願願',
    english: 'Wish',
    meaning: '願望',
    element: 'light',
    rarity: 'legendary',
    description: '傳說中能實現願望的字靈。只有最努力學習的探險家才見得到牠。',
    baseHp: 40,
    baseAtk: 17,
    look: {
      body: 'blob',
      color: '#fff7ed',
      belly: '#ffffff',
      eyes: 'happy',
      mouth: 'smile',
      accent: '#fbbf24',
      parts: ['crown', 'halo', 'wings', 'star'],
      cheeks: true,
    },
  },
];

/** 顯示用名字：進化後加上「超級」 */
export const creatureName = (s: Species, stage = 1) => (stage >= 2 ? `超級${s.name}` : s.name);
export const creatureEnglish = (s: Species, stage = 1) =>
  stage >= 2 ? `Super ${s.english}` : s.english;

/** 一開始可以選的夥伴 */
export const STARTER_IDS = [1, 2, 3] as const;

export const getSpecies = (id: number): Species => {
  const s = SPECIES.find((x) => x.id === id);
  if (!s) throw new Error(`Unknown species ${id}`);
  return s;
};
