import type { NewWord } from '../../domain';
const c10_1 = [
  { english: 'apartment', chinese: '公寓' },
  { english: 'bookstore', chinese: '書店' },
  { english: 'bridge', chinese: '橋' },
  { english: 'camp', chinese: '露營' },
  { english: 'church', chinese: '教堂' },
  { english: 'club', chinese: '球杆，或社團/俱樂部' },
  { english: 'department store', chinese: '百貨公司' },
  { english: 'factory', chinese: '工廠' },
  { english: 'hotel', chinese: '旅館' },
  { english: 'museum', chinese: '博物館' },
  { english: 'playground', chinese: '遊樂場' },
  { english: 'post office', chinese: '郵局' },
  { english: 'railway', chinese: '鐵路' },
  { english: 'restaurant', chinese: '餐館' },
  { english: 'sidewalk', chinese: '路邊行人道' },
  { english: 'supermarket', chinese: '超級市場' },
  { english: 'theater', chinese: '電影院' },
  { english: 'elementary school', chinese: '國小' },
  { english: 'junior high school', chinese: '國中' },
  { english: 'senior high school', chinese: '高中' },
].map((w) => ({ ...w, categories: ['10_1'] })) as Array<NewWord>;

const c10_2 = [
  { english: 'birthday', chinese: '生日' },
  { english: 'festival', chinese: '慶典' },
  { english: 'holiday', chinese: '假日' },
  { english: 'Christmas', chinese: '聖誕節' },
].map((w) => ({ ...w, categories: ['10_2'] })) as Array<NewWord>;

const c10_3 = [
  { english: 'large', chinese: '大' },
  { english: 'heavy', chinese: '重' },
  { english: 'light', chinese: '光/輕' },
  { english: 'high', chinese: '高 (位置、高度)' },
  { english: 'low', chinese: '低' },
  { english: 'fast', chinese: '快' },
  { english: 'quick', chinese: '快' },
  { english: 'loud', chinese: '大聲' },
  { english: 'quiet', chinese: '小聲/安靜' },
  { english: 'slow', chinese: '慢' },
  { english: 'cheap', chinese: '便宜' },
  { english: 'expensive', chinese: '貴' },
  { english: 'easy', chinese: '簡單' },
  { english: 'difficult', chinese: '困難' },
  { english: 'different', chinese: '不同的' },
  { english: 'same', chinese: '一樣的' },
  { english: 'least', chinese: '至少' },
  { english: 'less', chinese: '少' },
  { english: 'great', chinese: '太好/或大的' },
  { english: 'excellent', chinese: '太好了/傑出' },
  { english: 'common', chinese: '共同' },
  { english: 'favorite', chinese: '喜愛' },
  { english: 'full', chinese: '滿的' },
  { english: 'enough', chinese: '足夠' },
].map((w) => ({ ...w, categories: ['10_3'] })) as Array<NewWord>;

const c10_4 = [
  { english: 'appear', chinese: '出現' },
  { english: 'borrow', chinese: '借 (借入)' },
  { english: 'buy', chinese: '買' },
  { english: 'experience', chinese: '經驗' },
  { english: 'date', chinese: '日期' },
  { english: 'guess', chinese: '猜' },
  { english: 'forget', chinese: '忘記' },
  { english: 'hurt', chinese: '痛或傷害' },
  { english: 'join', chinese: '參加' },
  { english: 'lend', chinese: '借 (借出)' },
  { english: 'lie', chinese: '謊言或說謊' },
  { english: 'lose', chinese: '輸' },
  { english: 'mean', chinese: '卑鄙，或意思' },
  { english: 'meet', chinese: '遇見' },
  { english: 'miss', chinese: '想念' },
  { english: 'notice', chinese: '通知' },
  { english: 'order', chinese: '點單、命令或訂單' },
  { english: 'pay', chinese: '付錢' },
  { english: 'plan', chinese: '計劃' },
  { english: 'remember', chinese: '記得' },
  { english: 'save', chinese: '省(錢)、存放或救' },
  { english: 'sell', chinese: '賣' },
  { english: 'stay', chinese: '停留' },
  { english: 'understand', chinese: '了解' },
  { english: 'visit', chinese: '探訪' },
  { english: 'wake', chinese: '醒來' },
].map((w) => ({ ...w, categories: ['10_4'] })) as Array<NewWord>;

const c10_6 = [
  { english: 'convenient', chinese: '方便' },
  { english: 'correct', chinese: '正確或修改' },
  { english: 'dangerous', chinese: '危險' },
  { english: 'fine', chinese: '好' },
  { english: 'fresh', chinese: '新鮮' },
  { english: 'hard', chinese: '硬或難' },
  { english: 'helpful', chinese: '有幫助的' },
  { english: 'OK', chinese: '可以' },
  { english: 'possible', chinese: '可能' },
  { english: 'ready', chinese: '準備' },
  { english: 'real', chinese: '真實' },
  { english: 'right', chinese: '對或右邊' },
  { english: 'safe', chinese: '安全' },
  { english: 'true', chinese: '真實' },
  { english: 'useful', chinese: '好好使用/方便' },
  { english: 'wrong', chinese: '錯' },
].map((w) => ({ ...w, categories: ['10_6'] })) as Array<NewWord>;

const c10_7 = [
  { english: 'about', chinese: '大概' },
  { english: 'along', chinese: '延著' },
  { english: 'already', chinese: '已經' },
  { english: 'also', chinese: '也' },
  { english: 'around', chinese: '周圍' },
  { english: 'away', chinese: '離開' },
  { english: 'else', chinese: '其他' },
  { english: 'even', chinese: '雙數或持平' },
  { english: 'finally', chinese: '最終' },
  { english: 'friendly', chinese: '友善的' },
  { english: 'off', chinese: '關/離開' },
  { english: 'quite', chinese: '相當的' },
  { english: 'really', chinese: '真的' },
  { english: 'round', chinese: '圓的或回台' },
  { english: 'still', chinese: '仍然' },
  { english: 'together', chinese: '一起' },
].map((w) => ({ ...w, categories: ['10_7'] })) as Array<NewWord>;
export default [...c10_1, ...c10_2, ...c10_3, ...c10_4, ...c10_6, ...c10_7];
