import type { NewWord } from '../../domain';
const c9_1 = [
  { english: 'world', chinese: '世界' },
  { english: 'earth', chinese: '地球' },
  { english: 'place', chinese: '地方' },
  { english: 'somewhere', chinese: '某些地方' },
  { english: 'America', chinese: '美國' },
  { english: 'China', chinese: '大陸' },
  { english: 'Taiwan', chinese: '台灣' },
  { english: 'American', chinese: '美國的/美洲' },
  { english: 'Chinese', chinese: '中文' },
  { english: 'English', chinese: '英文' },
  { english: 'foreigner', chinese: '外國人' },
].map((w) => ({ ...w, categories: ['9_1'] })) as Array<NewWord>;

const c9_2 = [
  { english: 'business', chinese: '生意' },
  { english: 'garbage', chinese: '垃圾' },
  { english: 'machine', chinese: '機器' },
  { english: 'magic', chinese: '魔術' },
  { english: 'medicine', chinese: '藥' },
  { english: 'meeting', chinese: '會議' },
  { english: 'menu', chinese: '菜單' },
  { english: 'movie', chinese: '電影' },
  { english: 'news', chinese: '報紙' },
  { english: 'noise', chinese: '噪音' },
  { english: 'sale', chinese: '拍賣' },
  { english: 'vacation', chinese: '假期' },
  { english: 'money', chinese: '錢' },
  { english: 'price', chinese: '價錢' },
].map((w) => ({ ...w, categories: ['9_2'] })) as Array<NewWord>;

const c9_3 = [
  { english: 'chance', chinese: '機會' },
  { english: 'case', chinese: '盒子' },
  { english: 'example', chinese: '例子' },
  { english: 'fact', chinese: '事實' },
  { english: 'fire', chinese: '火' },
  { english: 'ground', chinese: '地面' },
  { english: 'hard-working', chinese: '認真工作' },
  { english: 'heat', chinese: '熱' },
  { english: 'idea', chinese: '點子' },
  { english: 'knowledge', chinese: '知識' },
  { english: 'list', chinese: '單子' },
  { english: 'matter', chinese: '事情/物體' },
  { english: 'mistake', chinese: '錯誤' },
  { english: 'problem', chinese: '問題' },
  { english: 'program', chinese: '節目' },
  { english: 'question', chinese: '問題' },
  { english: 'seat', chinese: '座位' },
  { english: 'simple', chinese: '簡單' },
  { english: 'size', chinese: '尺寸' },
  { english: 'song', chinese: '歌' },
  { english: 'sound', chinese: '聽或聲音' },
  { english: 'thing', chinese: '東西' },
  { english: 'trouble', chinese: '麻煩/問題' },
  { english: 'voice', chinese: '聲音' },
  { english: 'way', chinese: '路/方法' },
].map((w) => ({ ...w, categories: ['9_3'] })) as Array<NewWord>;

const c9_4 = [
  { english: 'agree', chinese: '同意' },
  { english: 'believe', chinese: '相信' },
  { english: 'care', chinese: '照顧' },
  { english: 'cheat', chinese: '作弊' },
  { english: 'cheer', chinese: '激勵' },
  { english: 'cry', chinese: '哭' },
  { english: 'decide', chinese: '決定' },
  { english: 'enjoy', chinese: '享受' },
  { english: 'excuse', chinese: '藉口' },
  { english: 'hope', chinese: '希望' },
  { english: 'interest', chinese: '興趣/嗜好' },
  { english: 'kiss', chinese: '親' },
  { english: 'mind', chinese: '介意' },
  { english: 'need', chinese: '需要' },
  { english: 'please', chinese: '請' },
  { english: 'surprise', chinese: '驚訝' },
  { english: 'welcome', chinese: '歡迎' },
  { english: 'wish', chinese: '希望' },
  { english: 'worry', chinese: '擔心' },
].map((w) => ({ ...w, categories: ['9_4'] })) as Array<NewWord>;

const c9_5 = [
  { english: 'burn', chinese: '燒傷' },
  { english: 'celebrate', chinese: '慶祝' },
  { english: 'check', chinese: '檢查' },
  { english: 'collect', chinese: '收集' },
  { english: 'copy', chinese: '影印/複製' },
  { english: 'cost', chinese: '成本' },
  { english: 'exercise', chinese: '練習' },
  { english: 'happen', chinese: '發生' },
  { english: 'practice', chinese: '練習' },
  { english: 'prepare', chinese: '準備' },
  { english: 'spend', chinese: '花錢' },
  { english: 'count', chinese: '數/算' },
  { english: 'die', chinese: '死去' },
  { english: 'dream', chinese: '夢' },
  { english: 'dress', chinese: '穿' },
  { english: 'dry', chinese: '乾' },
  { english: 'fill', chinese: '滿' },
  { english: 'finish', chinese: '完成' },
  { english: 'grow', chinese: '成長' },
  { english: 'hurry', chinese: '趕緊' },
  { english: 'live', chinese: '住' },
  { english: 'pack', chinese: '包' },
  { english: 'paint', chinese: '油漆' },
  { english: 'repeat', chinese: '重複' },
  { english: 'rest', chinese: '休息' },
  { english: 'shop', chinese: '商店' },
  { english: 'sleep', chinese: '睡覺' },
  { english: 'spell', chinese: '拼字' },
].map((w) => ({ ...w, categories: ['9_5'] })) as Array<NewWord>;

const c9_6 = [
  { english: 'as', chinese: '當作' },
  { english: 'because', chinese: '因為' },
  { english: 'but', chinese: '但是' },
  { english: 'during', chinese: '之間' },
  { english: 'except', chinese: '除了' },
  { english: 'if', chinese: '如果' },
  { english: 'or', chinese: '或' },
  { english: 'perhaps', chinese: '或許' },
  { english: 'since', chinese: '自從' },
  { english: 'so', chinese: '如此' },
  { english: 'than', chinese: '比' },
  { english: 'though (although)', chinese: '雖然' },
  { english: 'until', chinese: '直到' },
  { english: 'with', chinese: '跟' },
  { english: 'without', chinese: '沒有' },
].map((w) => ({ ...w, categories: ['9_6'] })) as Array<NewWord>;

export default [...c9_1, ...c9_2, ...c9_3, ...c9_4, ...c9_5, ...c9_6];
